### ISSUE TITLE
Goal descriptions are written into game.tw-pddl files 

### ISSUE THREAD

**Issue by MohitShridhar** [alfworld/alfworld#1]
Currently, the goal descriptions are written into game.tw-pddl files. This leads to race conditions during parallel runs.

**Comment by vzhong** [comment]
Sorry for reviving the dead here but is this still an issue @MarcCote ? I want to use ALFWorld as an example for tutorials for NLP/ML/RL. As a part of the tutorial I want to illustrate parallelization via multi-processing. It seems like I might be encountering this race condition @MohitShridhar mentioned here. In particular, the PDDL files get corrupted and then subsequent processes cannot deserialize JSON successfully from the game files. Deleting all data files and redownloading them solves the problem.

**Comment by MarcCote** [comment]
Working on a two-step process where users will first call `generate_tw_pddl.py` to generate the game files, then launch their training experiments on the generated tw-pddl which will remain static.

**Comment by MarcCote** [comment]
@vzhong if you want to give the PR (#53) a try to make sure it works with your workflow, that would be appreciated. This is the command you want to use to re-generate the games so they use the human annotations.

    python scripts/generate_tw_pddl.py --data_path $ALFWORLD_DATA/json_2.1.1 --save_path custom_dataset/ --goal_desc_human_anns_prob 1

Then you need to change the appropriate settings in the yaml
```yaml
dataset:
  data_path: 'custom_dataset/train'
  eval_id_data_path: 'custom_dataset/valid_seen'   
  eval_ood_data_path: 'custom_dataset/valid_unseen' 
```

**Comment by vzhong** [comment]
Yes I think this works - thank you! Can we please make this a command similar to `alfworld-download`? this way the user doesn't need to clone the repo and can instead just pip install it? Other than that look great to me!

**Comment by MarcCote** [comment]
Done. The command is now

     alfworld-generate --data_path $ALFWORLD_DATA/json_2.1.1 --save_path custom_dataset/ --goal_desc_human_anns_prob 1
