### ISSUE TITLE
Making observations reproducible

### ISSUE THREAD

**Issue by vmicheli** [alfworld/alfworld#14]
Hi,

When running the following snippet twice with `base_config.yaml` I'm not getting the same initial observation: 

```
config = generic.load_config()
np.random.seed(42)
torch.manual_seed(42)
torch.backends.cudnn.deterministic = True
torch.cuda.manual_seed(42)

env = getattr(environment, 'AlfredTWEnv')(config, train_eval='train')  
env = env.init_env(batch_size=1)
env.seed(42)

obs, info = env.reset()
print(obs[0])
```

For instance I get:

`you see a drawer 8, a drawer 4, a toilet 1, a sinkbasin 1, a drawer 7, a handtowelholder 1, a countertop 1, a drawer 3, a drawer 5, a drawer 6, a drawer 2, a toiletpaperhanger 1, a garbagecan 1, a drawer 1, a towelholder 1, and a sinkbasin 2.`

and

`you see a drawer 2, a garbagecan 1, a sinkbasin 2, a drawer 5, a toilet 1, a sinkbasin 1, a drawer 1, a drawer 6, a handtowelholder 1, a countertop 1, a drawer 8, a drawer 7, a drawer 4, a drawer 3, a toiletpaperhanger 1, and a towelholder 1.`

The task is the same but the ordering and numbering of objects is different.

Which step am I missing to ensure reproducibility?

**Comment by xingdi-eric-yuan** [comment]
Hi @vmicheli. In the code preprocessing the input, we manually sort this list. We keep the shuffled observation list in the environment, so that future systems can leverage this weak data augmentation feature. However, in the agent reported in our paper, we assume a fixed object order.

**Comment by MohitShridhar** [comment]
That's right. More info on this: `domain_randomization` in the [config file](https://github.com/alfworld/alfworld/blob/c0501c807fa77dd25ecfc86e92cd782226f5c74f/configs/base_config.yaml#L15) affects the [shuffling here](https://github.com/alfworld/alfworld/blob/c0501c807fa77dd25ecfc86e92cd782226f5c74f/alfworld/agents/utils/misc.py#L28).

**Comment by vmicheli** [comment]
Thanks for your answers!

Regarding `domain_randomization`, I'm not sure I understand its role. It is already set to `False` in the config file but the environment still produces shuffled observations from one run to another.

**Comment by MohitShridhar** [comment]
Oops sorry @vmicheli I misread the question. Right, this `domain_randomization` is only for shuffling object ID numbers. The order of the objects in the sentence is perturbed by something else in Textworld. CC'ing @MarcCote.

But as Eric pointed out, we sort the objects to circumvent this.

**Comment by MarcCote** [comment]
@vmicheli thanks for reporting this. I've pushed a commit that should ensure the reproducibility of the observation. Please reinstall the following custom version of TextWorld
```
pip uninstall textworld
pip install https://github.com/MarcCote/TextWorld/archive/handcoded_expert_integration.zip
```

For reference, the fix was to sort the variable assignments (see https://github.com/MarcCote/TextWorld/commit/2e6dd1870dcf9a626c239ec713f5ea0764939cbb).

Let us know if that fixes it for you.

**Comment by vmicheli** [comment]
Indeed the fix solves my issue. Thank you for the quick follow-up guys!
