### ISSUE TITLE
Permission denied in Docker Setup

### ISSUE THREAD

**Issue by yipliu** [alfworld/alfworld#17]
Hi,
When I run  
```python
python docker/docker_build.py
```
I get this error
```bin
Step 14/32 : COPY ./docker/install_deps.sh /tmp/install_deps.sh
 ---> Using cache
 ---> 8e86891f19f0
Step 15/32 : RUN yes "Y" | /tmp/install_deps.sh
 ---> Running in 75a86a4cad1b
/bin/sh: 1: /tmp/install_deps.sh: Permission denied
```
I have added my user name to the docker group

**Comment by MohitShridhar** [comment]
@yipliu can you run `chmod +x docker/install_deps.sh` before running the python script?

This also might be helpful: https://stackoverflow.com/questions/38882654/docker-entrypoint-running-bash-script-gets-permission-denied/38882798

**Comment by yipliu** [comment]
WOW! Thank you!
