### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'lspci'

### ISSUE THREAD

**Issue by yipliu** [alfworld/alfworld#19]
Hi,
I met the same problem [#51](https://github.com/askforalfred/alfred/issues/51) opened in alfred, when I run this command in alworld.
```bash
sudo python ~/alfworld/docker/startx.py 0 
```
> Actually, I run **sudo python3 ~~/alfworld/docker/startx.py 0** 
It shows
```bash
Starting X on DISPLAY=:0
Traceback (most recent call last):
  File "/home/lyp/alfworld/docker/startx.py", line 97, in <module>
    startx(display)
  File "/home/lyp/alfworld/docker/startx.py", line 72, in startx
    for r in pci_records():
  File "/home/lyp/alfworld/docker/startx.py", line 15, in pci_records
    output = subprocess.check_output(command).decode()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'lspci'
```
Do I need the same change?

**Comment by MohitShridhar** [comment]
@yipliu I added `pciutils` to [install_deps.sh](https://github.com/alfworld/alfworld/blob/master/docker/install_deps.sh#L39). Try it out now.

**Comment by yipliu** [comment]
Everything works!!!
BTW, do you know of a detailed tutorial on deep learning with Docker?

**Comment by MarcCote** [comment]
@yipliu thanks a lot for reporting this issue. Regarding your question, I don't have a lot of experience with running deep learning experiments with Docker other than re-using existing docker from dockerhub and running my code on them interactively.

**Comment by yipliu** [comment]
@MarcCote, developing with VScode and Docker is an extraordinary experience! It makes me wonder what excellent engineers do when they do R&D. However, as a student, I will focus on improving the model's performance. Thank you for your reply!
