### ISSUE TITLE
Runtime errors of testing scripts

### ISSUE THREAD

**Issue by zhaozj89** [alfworld/alfworld#2]
Hi, thanks for this work.

When I ran scripts here `https://github.com/alfworld/alfworld/tree/master/scripts`, there were some errors.

For TextWorld, it said, `TypeError: __init__() got an unexpected keyword argument 'wrappers'`. I installed your customized TextWorld https://github.com/MohitShridhar/TextWorld, but it still reported this error.

![image](https://user-images.githubusercontent.com/34164876/97872785-938d4e80-1d51-11eb-8a72-af737d8fcf0c.png)

For THOR, it reported `Segmentation fault (core dumped)`. I have no clue how to fix this.

![image](https://user-images.githubusercontent.com/34164876/97872911-c5061a00-1d51-11eb-8e31-559068bf72c8.png)

Could you give me some clues of them? Thanks for your time.

**Comment by MohitShridhar** [comment]
@zhaozj89 are you using the right branch for Textworld: https://github.com/MohitShridhar/TextWorld/tree/handcoded_expert_integration

For THOR, can you run `python docker/check_thor.py` and report back? If the segfault still persists, can you post a [stacktrace](https://docs.python.org/3/library/faulthandler.html)?

**Comment by zhaozj89** [comment]
Thanks for your reply. Both work. Sorry for my carelessness.

**Comment by zhaozj89** [comment]
Hi, when I ran `python scripts/play_alfred_thor.py data/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller mrcnn_astar --debug`, where I want to try MRCNN. It gave me the following errors. Is the command right? The readme said using `--agent mrcnn_astar`, but this does not work. Thanks.

`RuntimeError: unexpected EOF, expected 132923 more bytes. The file might be corrupted.`

![Screenshot 2020-11-09 at 9 16 42 PM](https://user-images.githubusercontent.com/34164876/98545762-ea0a0800-22d0-11eb-92fb-6f780daf38fa.png)

**Comment by MohitShridhar** [comment]
@zhaozj89 it looks like the checkpoint was somehow corrupted. Can you remove `mrcnn.pth` and directly download it without the script: `wget https://aka.ms/alfworld/mrcnn.pth`?

**Comment by zhaozj89** [comment]
This works. Thank you for the support!
