### ISSUE TITLE
alfred2textworld

### ISSUE THREAD

**Issue by tongzhoumu** [alfworld/alfworld#22]
Hi ALFWorld authors,

Is [this file](https://github.com/alfworld/alfworld/blob/master/scripts/alfred2textworld.py) used to convert an Alfred game to a textworld game? If so, how to use this script? Can you give a simple example?

Thank you so much!

**Comment by MarcCote** [comment]
Hi @tongzhoumu, a better example would be [alfworld-play-tw](https://github.com/alfworld/alfworld/blob/master/scripts/alfworld-play-tw). In that script, you can see we are loading the `.pddl` file directly along with the [ALFWorld logic and grammar data](https://github.com/alfworld/alfworld/tree/master/alfworld/data). It works differently from how TextWorld traditionally generates Z-Machine games (.z8).

Let us know if that's not what you are looking for.

**Note** that you need a [specific version of TextWorld](https://github.com/alfworld/alfworld/blob/master/requirements.txt#L31-L32).

**Comment by tongzhoumu** [comment]
Hi Marc,

Thanks for your reply!

I am looking for something can convert `.pddl` file into `.z8` file. More specifically, I wish the `facts` can be accessed from `info` returned by the environment. I guess `.z8` file is needed in this case?

I think [these lines](https://github.com/alfworld/alfworld/blob/master/scripts/alfred2textworld.py#L66-L176) are similar to what I need, which extracts `facts` from `.pddl` file. However, the rest part of [the script](https://github.com/alfworld/alfworld/blob/master/scripts/alfred2textworld.py) cannot be successfully run. So I am wondering how to convert `.pddl` to `.z8` files.

Any suggestions are appreciated. Thank you!

**Comment by MarcCote** [comment]
The main issue with converting `.pddl` to `.z8` games is PDDL language is much more expressive than what the predicate logic TextWorld uses. The main limitation is due to the fact that TextWorld doesn't support quantifiers. For instance, in PDDL turning on the microwave will heat **all** items inside of it, but in TextWorld we can only heat one item at a time (which needs to be specified explicitly).

Can I ask why you need `.z8` games?

**Comment by tongzhoumu** [comment]
I want to get the `facts` by setting `request_infos.fact = True` when registering the games. But when I did it, I fount that I got `None` from the `info` returned by the environment. I guess this is because `.pddl` files do not directly include the `facts`. And I found [these lines](https://github.com/alfworld/alfworld/blob/master/scripts/alfred2textworld.py#L66-L176) look like extracting facts from `.pddl` and dump them into `.z8`, so I guess I need to convert `.pddl` into `.z8` in order to get `facts`.

Is this the correct way to get `facts`?

**Comment by MarcCote** [comment]
If you simply want the facts, there's no need for generating `.z8` games. In [textworld-play-tw](https://github.com/alfworld/alfworld/blob/master/scripts/alfworld-play-tw),  replace the class `AlfredDemangler` with the following:

```python
class AlfredDemangler(textworld.core.Wrapper):

    def _clean_alfred_facts(self, facts):
        # def _clean_fact(fact: textworld.logic.Proposition):
        #     args = [textworld.logic.Variable(self.demangler.demangle_alfred_name(arg.name), arg.type) for arg in fact.arguments]
        #     return textworld.logic.Proposition(fact.name, args)

        def _clean_fact_simple(fact: textworld.logic.Proposition):
            args = [self.demangler.demangle_alfred_name(arg.name) for arg in fact.arguments]
            return (fact.name, *args)

        # facts = [_clean_fact(fact) for fact in facts if not fact.name.startswith("new-axiom@")]
        facts = [_clean_fact_simple(fact) for fact in facts if not fact.name.startswith("new-axiom@")]
        return facts

    def load(self, *args, **kwargs):
        super().load(*args, **kwargs)

        self.demangler = Demangler(game_infos=self._game.infos)
        for info in self._game.infos.values():
            info.name = self.demangler.demangle_alfred_name(info.id)

    def step(self, command: str):
        result = super().step(command)

        if self.infos.facts:
            self.state["facts"] = self._clean_alfred_facts(self.state["_facts"])

        return result

    def reset(self):
        result = super().reset()

        if self.infos.facts:
            self.state["facts"] = self._clean_alfred_facts(self.state["_facts"])

        return result
```

**Comment by MarcCote** [comment]
Hi @tongzhoumu did that end up working for you?

**Comment by tongzhoumu** [comment]
Hi @MarcCote , it works. Thank you so much!

I have an additional question: I noticed that the facts do not include the information about the goal. Is there any way to get the "facts" about the goal of the game?

**Comment by MarcCote** [comment]
In ALFRED/ALFWorld the goal is not defined by a predefined set of facts, rather it is a function/axiom, i.e. is there an object (or group of objects) that satisfies the goal conditions. For instance, take a task like "Put a fork in the sink.", it is easy to see that the agent could put any fork it can find in the sink in order to complete the task. This would translate into a function/axiom like this:
```
Axiom goal()                                                                                                                                           
  Conjunction
    Atom objecttype(?o, forktype)
    Atom receptacletype(?r, sinkbasintype)
    Atom inreceptacle(?o, ?r)
```
Note the use of variables `?o` and `?r` instead of concrete objects (i.e., `fork_bar__minus_00_dot_66_bar__plus_00_dot_90_bar__plus_01_dot_25`, `sink_bar__minus_01_dot_70_bar__plus_00_dot_73_bar__plus_03_dot_83_bar_sinkbasin`).

With all that being said, you can get that function/axiom using the following code (i.e., a modified version of the `AlfredDemangler` posted earlier):
```python
class AlfredDemangler(textworld.core.Wrapper):

    def _clean_alfred_facts(self, facts):
        # def _clean_fact(fact: textworld.logic.Proposition):
        #     args = [textworld.logic.Variable(self.demangler.demangle_alfred_name(arg.name), arg.type) for arg in fact.arguments]
        #     return textworld.logic.Proposition(fact.name, args)

        def _clean_fact_simple(fact: textworld.logic.Proposition):
            args = [self.demangler.demangle_alfred_name(arg.name) for arg in fact.arguments]
            return (fact.name, *args)

        # facts = [_clean_fact(fact) for fact in facts if not fact.name.startswith("new-axiom@")]
        facts = [_clean_fact_simple(fact) for fact in facts if not fact.name.startswith("new-axiom@")]
        return facts

    def load(self, *args, **kwargs):
        super().load(*args, **kwargs)

        self.demangler = Demangler(game_infos=self._game.infos)
        for info in self._game.infos.values():
            info.name = self.demangler.demangle_alfred_name(info.id)

    def step(self, command: str):
        result = super().step(command)

        if self.infos.facts:
            self.state["facts"] = self._clean_alfred_facts(self.state["_facts"])

        if "goal" in self.infos.extras:
            self.state["extra.goal"] = self.goal_conditions

        return result

    def reset(self):
        result = super().reset()

        if self.infos.facts:
            self.state["facts"] = self._clean_alfred_facts(self.state["_facts"])

        if "goal" in self.infos.extras:
            task = self._game_progression.state.task
            for axiom in task.axioms:
                if axiom.name == task.goal.predicate:
                    break
            else:
                axiom = None

            assert axiom is not None, "Should never happen in ALFWorld."
            assert not axiom.condition.has_disjunction(), "Should never happen in ALFWorld."

            self.goal_conditions = [(atom.predicate, *atom.args) for atom in axiom.condition.parts]
            self.state["extra.goal"] = self.goal_conditions

        return result
```
Note that you need to set `request_infos.extras.append("goal")`, then can be retrieved like so `infos['extra.goal']`.
