### ISSUE TITLE
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.

### ISSUE THREAD

**Issue by IpadLi** [alfworld/alfworld#27]
Hi, when I use the command `pip install alfworld`, it shows that:

     ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI. 
     alfworld depends on fast-downward@ https://github.com/MarcCote/downward/archive/faster_replan.zip

I have tried the following method:

First, I manually install `fast-downward`, and I check this by `conda list` and see that this has been installed (but the channel is pypi, may be this is the problem).

Second, I install `alfworld` by ignoring the installed dependency `pip install alfworld --ignore-installed fast-downward`.

But this still cannot install `alfworld`, and still gives the same error message.

Could you please give some comments on this?

**Comment by MohitShridhar** [comment]
@IpadLi, have you followed the instructions [here](https://github.com/alfworld/alfworld#quickstart)?

```
$ pip install https://github.com/MarcCote/downward/archive/faster_replan.zip
$ pip install https://github.com/MarcCote/TextWorld/archive/handcoded_expert_integration.zip
$ pip install alfworld
```

**Comment by IpadLi** [comment]
@MohitShridhar yes, I follow these three instructions, the first two can be executed successfully, but when installing alfworld, it shows the error.

**Comment by MarcCote** [comment]
It looks like PyPI is now making sure dependents packages are also listed on PyPI (which is not the case for my custom fast-downward and TextWorld branches).

For now, you could git clone the Alfworld repo and install alfworld from the local source.
> pip install alfworld/

I also notice we were using an older version of torch=1.2.0 which doesn't seem to be pip installable anymore :/.

**Comment by MarcCote** [comment]
I was able to run `alfworld-play-tw` following this procedure. Let us know if that works for you.

```
apt install cmake  # Needed for compiling fast-downward 

conda create -n alfworld36 python=3.6
conda activate alfworld36

git clone https://github.com/alfworld/alfworld.git alfworld
cd alfworld
pip install -r requirements.txt
pip install .
alfworld-download
alfworld-play-tw
```

**Comment by IpadLi** [comment]
@MarcCote This works for me. Thanks a lot.

> I was able to run `alfworld-play-tw` following this procedure. Let us know if that works for you.

Also, as this repo depends on an older version of torch=1.2.0, the Python version needs to be `<3.8.0a0`. Before @MarcCote 's solution, I tried this: I create a conda env with `python=3.9` and try to install `torch=1.2.0` because this repo depends on this torch version, and then it found conflicts:

` - pytorch==1.2.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0'] `
` - torchvision==0.4.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0'] `

**Comment by MohitShridhar** [comment]
Thanks @MarcCote for looking into this! I have updated the README [here](https://github.com/alfworld/alfworld#quickstart)

@IpadLi, this repo is quite old (2020), so you probably have to upgrade some dependencies.

**Comment by alxfed** [comment]
Closing the issue in which the complete and detailed instructions provided by the author so that they would become invisible...is just... charming. :)

**Comment by MohitShridhar** [comment]
Good point. Keeping it open for future reference.
