### ISSUE TITLE
Stuck at resetting Thorenv

### ISSUE THREAD

**Issue by Oscarchen2020** [alfworld/alfworld#29]
Sorry, I stuck at this step and no task display, can anyone help? thanks
Test on vmware virtual machine

![螢幕擷取畫面 2023-04-28 135235](https://user-images.githubusercontent.com/67366385/235065591-81974981-ec2a-4c2c-8789-f70a8913873e.png)

**Comment by MohitShridhar** [comment]
@Oscarchen2020, can check where exactly the script is getting stuck in [this function](https://github.com/alfworld/alfworld/blob/253b76dc848823db7348ac04525cdfc40527e80b/alfworld/env/thor_env.py#L54)?

Is it the `Initialize` action? or `self.task.reset()` or `self.reset_states()`?

**Comment by kittyjiang880831** [comment]
![image](https://user-images.githubusercontent.com/61786619/236660946-afeac62c-4c76-4eea-a979-2c031c1c1584.png)
It seems like error in the initial part.

**Comment by MohitShridhar** [comment]
Can you post the full `alfworld-tw-play` command with arguments? Also, can you check the `/home/mshr/.config/unity/Allen Institute../AI2-Thor/Player.log`? and post it here?

This might be related to some general issues with THOR: https://github.com/allenai/ai2thor/issues/903

**Comment by Oscarchen2020** [comment]
YES, We have solved the problem.

**Comment by RishiHazra** [comment]
@Oscarchen2020 @kittyjiang880831 
I'm facing the same issue. How did you resolve it? Thank You!

**Comment by Oscarchen2020** [comment]
@RishiHazra I think it's because we implement on vmware virtual machine where there is no real GPU. Therefore, I try to implement it on my server, and then it works.
