### ISSUE TITLE
Make ALFWorld PyPi package and remove dependency on ALFRED_ROOT

### ISSUE THREAD

**Issue by MohitShridhar** [alfworld/alfworld#3]
Make ALFWorld a PyPi package and remove dependency on `ALFRED_ROOT`

**Comment by MarcCote** [comment]
@MohitShridhar  Let me know if you need help with that.

**Comment by MohitShridhar** [comment]
@MarcCote, that would be great! Ideally, this should simplify [ALFWorld TW](https://github.com/alfworld/alfworld/blob/master/scripts/play_alfred_tw.py) usage, so that users can directly install the pip package and start interacting with environment.

**Comment by MarcCote** [comment]
Oh. I forgot about this. I'll try to do it next week.

**Comment by MohitShridhar** [comment]
Done! Merged to master.
