### ISSUE TITLE
Stack to "Resetting ThorEnv" when running quickstart with Random Agent for env type "AlfredThorEnv"

### ISSUE THREAD

**Issue by gtziafas** [alfworld/alfworld#34]
Hey! This is a great work, thanks so much for making it available!

I have successfully run the quickstart-with-random-agent code snippet:
```
import numpy as np
import alfworld.agents.environment as environment
import alfworld.agents.modules.generic as generic

# load config
config = generic.load_config()
env_type = config['env']['type'] # 'AlfredTWEnv' or 'AlfredThorEnv' or 'AlfredHybrid'

# setup environment
env = getattr(environment, env_type)(config, train_eval='train')
env = env.init_env(batch_size=1)

# interact
obs, info = env.reset()
while True:
    # get random actions from admissible 'valid' commands (not available for AlfredThorEnv)
    admissible_commands = list(info['admissible_commands']) # note: BUTLER generates commands word-by-word without using admissible_commands
    random_actions = [np.random.choice(admissible_commands[0])]

    # step
    obs, scores, dones, infos = env.step(random_actions)
    print("Action: {}, Obs: {}".format(random_actions[0], obs[0]))
```
for the `AlfredTWEnv` environment type option. When I'm attempting to do it for the `AlfredThorEnv`, the env is initialized propertly, the Unity engine begins and I can see a frame of the environment, but then it gets stuck at the `obs, info = env.reset()` line. I can see the "Resetting ThorEnv" message in the console, but then the script hangs there. 

This is my console output:
```
Initialize AlfredThorEnv...
Overall we have 4639 games...
Training with 4639 games
Overall we have 4639 games...
Training with 4639 games
Found path: /home/ggtz/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/ggtz/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/ggtz/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1920x1080 (primary device).
Logging to /home/ggtz/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
ThorEnv started.
Resetting ThorEnv
```
Do you maybe have any idea why?

**Comment by MohitShridhar** [comment]
@gtziafas can you paste the output of `/home/ggtz/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log` ?

**Comment by MarcCote** [comment]
@gtziafas great news. Please do share the changes you've made here :). Others might be facing the same issue.

**Comment by ishikasingh** [comment]
This worked for me: `pip install Werkzeug==2.0.3` with `ai2thor==2.1.0`
https://github.com/alexpashevich/E.T./issues/8#issuecomment-1299451176

**Comment by MarcCote** [comment]
Thanks @ishikasingh, `werkzeug==2.0.3` is now added to `requirements.txt` in ALFWorld 0.3.2.

    pip install -U alfworld
