### ISSUE TITLE
Could you tell us the new checkpoint URLs?

### ISSUE THREAD

**Issue by maguro27** [alfworld/alfworld#35]
Hi.
When I ran the `python scripts/alfworld-download --extra`, I faced the following 409 error.
```
Traceback (most recent call last):
  File "scripts/alfworld-download", line 165, in <module>
    main()
  File "scripts/alfworld-download", line 139, in main
    zipped_filename = download(CHECKPOINTS_URL, dst=args.data_dir,
  File "scripts/alfworld-download", line 64, in download
    r.raise_for_status()  # Bad request.
  File "/home/maguro/alfworld_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Public access is not permitted on this storage account. for url: https://textworld.blob.core.windows.net/$web/datasets/tw-alfred/pretrained_checkpoints.zip
```

So, could you provide the new checkpoint URLs (pre-trained and seq2seq checkpoints)?
Thanks!

**Comment by MohitShridhar** [comment]
@maguro27, if I remember correctly, the zip file contains:
- Best seen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd234_id.pt 
- Best unseen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd432_ood.pt

**Comment by wenjunli-0** [comment]
> @maguro27, if I remember correctly, the zip file contains:
> 
> * Best seen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd234_id.pt
> * Best unseen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd432_ood.pt

Hi Mohit,
Where should I put these two models?  I met the same problem as @maguro27

**Comment by maguro27** [comment]
@MohitShridhar 

I appreciate for providing the checkpoints.

However, I have a question.
`Best seen` file means `CHECKPOINTS_URL` in alfworld-download?
And `Best unseen` file means `SEQ2SEQ_DATA_URL` in alfworld-download?

**Comment by wenjunli-0** [comment]
> @MohitShridhar
> 
> I appreciate for providing the checkpoints.
> 
> However, I have a question. `Best seen` file means `CHECKPOINTS_URL` in alfworld-download? And `Best unseen` file means `SEQ2SEQ_DATA_URL` in alfworld-download?

Hi maguro,
May I ask where you download the alfred.pddl file? When I put `python scripts/alfworld-download --extra`, it will throw out the same error as yours. And `alfworld-play-tw` would need the alfred.pddl file under <storage_path>/logic/alfred.pddl. Have you played the textgame?

**Comment by wenjunli-0** [comment]
> @MohitShridhar
> 
> I appreciate for providing the checkpoints.
> 
> However, I have a question. `Best seen` file means `CHECKPOINTS_URL` in alfworld-download? And `Best unseen` file means `SEQ2SEQ_DATA_URL` in alfworld-download?

Hi @maguro27 ,
May I ask where you download the alfred.pddl file? When I put python scripts/alfworld-download --extra, it will throw out the same error as yours. And alfworld-play-tw would need the alfred.pddl file under <storage_path>/logic/alfred.pddl. Have you played the textgame?

**Comment by maguro27** [comment]
@wenjunli-0 

Here. Good luck.
https://github.com/alfworld/alfworld/issues/32

**Comment by MarcCote** [comment]
> @maguro27, if I remember correctly, the zip file contains:
> 
> * Best seen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd234_id.pt
> * Best unseen: https://github.com/alfworld/alfworld/releases/download/0.2.2/f6b17e20_task1-2-3-4-5-6_IL_g_r1_sh0_ts0_o5_sd432_ood.pt

I added `pretrained_checkpoints.zip` to the latest release.
https://github.com/alfworld/alfworld/releases/download/0.2.2/pretrained_checkpoints.zip

**Comment by MarcCote** [comment]
I have changed all the URLs in the `alfworld-download` script to point to the files included in the latest release.
