### ISSUE TITLE
Unable to install dependency

### ISSUE THREAD

**Issue by MrCheesy21** [alfworld/alfworld#40]
Hi just following the instructions for setup, I am stuck installing the faster_replan package. Using a new conda env with python=3.6, I get the following error: 

![image](https://github.com/alfworld/alfworld/assets/25647903/c5e1ee9b-64c2-457e-a97d-61d5933bf5b9)

**Comment by MarcCote** [comment]
From the error message, it seems `cmake` is not installed. This is the requirements for installing Downward.
https://www.fast-downward.org/ObtainingAndRunningFastDownward

However, I'm not sure ALFWorld was tested for Windows. I suggest you use a [Docker container](https://github.com/alfworld/alfworld#docker-setup).

**Comment by MarcCote** [comment]
Should be solved in the upcoming release. In the meantime, try installing the release candidate mentioned in #44.
