### ISSUE TITLE
How to use alfworld for later version of torchvision and python?

### ISSUE THREAD

**Issue by bf-yang** [alfworld/alfworld#43]
I can install alfworld in python3.6 and torchvision 0.4.0, but for most of the current projects, these versions are out of date.
When I use python3.9 and torch 0.14.0, it reports: "pkg_resources.DistributionNotFound: The 'torchvision==0.4.0' distribution was not found and is required by alfworld" .

Could you please help me how to fix it problem? Thanks.

**Comment by mczhuge** [comment]
Thanks@[MarcCote](https://github.com/MarcCote) but it seems that the answer does not directly solve the question. Any more suggestion?
