### ISSUE TITLE
readme instructions not working

### ISSUE THREAD

**Issue by bhavanadalvi** [alfworld/alfworld#49]
We are trying to use ALFWorld as one of the datasets in our experiments. When I follow your instructions in [install source](https://github.com/alfworld/alfworld?tab=readme-ov-file#install-source ). 

I did create a python 3.9 virtualenv.
When I run "pip install -r requirements-full.txt"
I get the following error:

Collecting scipy (from visdom->-r requirements-full.txt (line 11))
  Downloading scipy-1.12.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.3 MB/s eta 0:00:00
Collecting tornado (from visdom->-r requirements-full.txt (line 11))
  Using cached tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl.metadata (2.5 kB)
Collecting six (from visdom->-r requirements-full.txt (line 11))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting jsonpatch (from visdom->-r requirements-full.txt (line 11))
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting websocket-client (from visdom->-r requirements-full.txt (line 11))
  Using cached websocket_client-1.7.0-py3-none-any.whl.metadata (7.9 kB)
Collecting fast-downward-textworld (from textworld[pddl]>=1.6.1->-r requirements-full.txt (line 6))
  Using cached fast_downward_textworld-20.6.1.tar.gz (627 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Building configuration library.
      Executing command "cmake -G Unix Makefiles -DCMAKE_BUILD_TYPE=Library -DDISABLE_PLUGINS_BY_DEFAULT=YES -DPLUGIN_LIBRARY_ENABLED=YES ../../src" in directory "/private/var/folders/br/_vmrb7yx7f7g8s3f82pd78tm0000gp/T/pip-install-fhgbhiwg/fast-downward-textworld_7da6712a0f3d495db8f47f0c098373d7/builds/library".
      Could not find 'cmake' on your PATH. For installation instructions, see http://www.fast-downward.org/ObtainingAndRunningFastDownward.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/br/_vmrb7yx7f7g8s3f82pd78tm0000gp/T/pip-install-fhgbhiwg/fast-

downward-textworld_7da6712a0f3d495db8f47f0c098373d7/setup.py", line 11, in <module>
          subprocess.check_call(['python', 'build.py', '--library'], cwd=BASEPATH)
        File "/opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['python', 'build.py', '--library']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MarcCote** [comment]
Good catch. Because ALFWorld indirectly depends on downward-textworld library, you need to have [cmake](https://cmake.org/download/) installed on your machine.

**Comment by MarcCote** [comment]
@bhavanadalvi did it work?

**Comment by bhavanadalvi** [comment]
Thanks @MarcCote for the help, yes, we are able to make it work at least on our linux machine.
