### ISSUE TITLE
install alfword[full] Error

### ISSUE THREAD

**Issue by GaoDalie** [alfworld/alfworld#55]
hey Authors

i tried many ways to install alfword[full] but still doesn't work 😢

could you help please 👍 

Collecting alfworld[full]
  Using cached alfworld-0.3.3-py3-none-any.whl (354 kB)
Collecting ai2thor==2.1.0 (from alfworld[full])
  Using cached ai2thor-2.1.0-py2.py3-none-any.whl (25 kB)
Collecting opencv-python (from alfworld[full])
  Using cached opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl (38.6 MB)
Collecting pandas (from alfworld[full])
  Using cached pandas-2.2.1-cp311-cp311-win_amd64.whl (11.6 MB)
Collecting textworld[pddl]>=1.6.1 (from alfworld[full])
  Using cached textworld-1.6.1.tar.gz (708 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torch (from alfworld[full])
  Using cached torch-2.2.1-cp311-cp311-win_amd64.whl (198.6 MB)
Collecting torchvision (from alfworld[full])
  Using cached torchvision-0.17.1-cp311-cp311-win_amd64.whl (1.2 MB)
Requirement already satisfied: tqdm in c:\users\user\desktop\test-webshop\venv\lib\site-packages (from alfworld[full]) (4.66.2)
Collecting werkzeug==2.0.3 (from alfworld[full])
  Using cached Werkzeug-2.0.3-py3-none-any.whl (289 kB)
Collecting h5py; extra == "full" (from alfworld[full])
  Using cached h5py-3.10.0-cp311-cp311-win_amd64.whl (2.7 MB)
Collecting pycocotools; extra == "full" (from alfworld[full])
  Using cached pycocotools-2.0.7-cp311-cp311-win_amd64.whl (85 kB)
Collecting transformers; extra == "full" (from alfworld[full])
  Using cached transformers-4.38.2-py3-none-any.whl (8.5 MB)
Collecting visdom; extra == "full" (from alfworld[full])
  Using cached visdom-0.2.4.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... done
Collecting flask (from ai2thor==2.1.0->alfworld[full])
  Using cached flask-3.0.2-py3-none-any.whl (101 kB)
Collecting numpy (from ai2thor==2.1.0->alfworld[full])
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Collecting pyyaml (from ai2thor==2.1.0->alfworld[full])
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Requirement already satisfied: requests in c:\users\user\desktop\test-webshop\venv\lib\site-packages (from ai2thor==2.1.0->alfworld[full]) (2.31.0)
Collecting progressbar2 (from ai2thor==2.1.0->alfworld[full])
  Using cached progressbar2-4.4.2-py3-none-any.whl (56 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\desktop\test-webshop\venv\lib\site-packages (from pandas->alfworld[full]) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas->alfworld[full])
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting tzdata>=2022.7 (from pandas->alfworld[full])
  Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Collecting cffi>=1.0.0 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached cffi-1.16.0-cp311-cp311-win_amd64.whl (181 kB)
Collecting networkx>=2 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting more-itertools (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached more_itertools-10.2.0-py3-none-any.whl (57 kB)
Collecting tatsu>=5.8.3 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached TatSu-5.11.3-py3-none-any.whl (79 kB)
Collecting hashids>=1.2.0 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached hashids-1.3.1-py2.py3-none-any.whl (6.6 kB)
Collecting jericho>=3.0.3 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached jericho-3.1.2.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      rm -f src/*.h src/*.a
      process_begin: CreateProcess(NULL, rm -f src/*.h src/*.a, ...) failed.
      make (e=2): The system cannot find the file specified.
      make: *** [Makefile:449: clean] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-w1srbcah\jericho\setup.py", line 26, in <module>
          subprocess.check_call(['make', 'clean'], cwd=FROTZPATH)
        File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> jericho

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by MarcCote** [comment]
Some of our dependencies don't support Windows system, so ALFWorld won't work either. One solution would be to use a docker installation.
https://github.com/alfworld/alfworld/tree/0.2.2?tab=readme-ov-file#docker-setup
