### ISSUE TITLE
About using "alfworld-play-thor" to perform the "pick_and_place_with_movable_recep" task

### ISSUE THREAD

**Issue by Zhen-ao** [alfworld/alfworld#57]
Hi, Thanks for your interesting work! 

I am playing an Embodied-World (THOR) game [_**alfworld-play-thor**_],  
but in the task of **"pick_and_place_with_movable_recep-xxx"**,  **it is not possible to put one object in/on another object.**

**For example:** In "pick_and_place_with_Movable_recip-apple-pot-countertop-4/trial_T20190907_183432_704642", I use the command `"put apple 1 in/on pot 1"` and **the "Apple" cannot be placed on the "Pot"**.  

Is my command wrong, or is this function not supported? If the function change is not supported, how can I modify the implementation?

The process I implemented is as follows:
![error](https://github.com/alfworld/alfworld/assets/38036089/8c1f2e65-9f1f-49af-a8c2-66e4935c991b)

**Comment by MarcCote** [comment]
Thanks for bringing this to our attention

Not all ALFRED games are supported for ALFWorld. For instance, the movable ones are not supported as briefly mentioned in the [scripts/README.md](https://github.com/alfworld/alfworld/tree/master/scripts)

> it means the game is unsolvable or the PDDL problem is ill-defined. Some tasks from ALFRED like **movable receptacle** tasks are not used in ALFWorld, and will fail if you try to load them with alfworld-play-tw.

That said, those play scripts should raise an error when loading those games. I'll look into it.

**Comment by jinzhao-SU** [comment]
I have the same issue. The terminal doesn't raise any error but shows "Nothing happens". It usually occurs in the tasks starting with "pick_and_place_with_movable_recep" when loading them with alfworld-play-thor.

**Comment by MarcCote** [comment]
With https://github.com/alfworld/alfworld/pull/58, those games won't load anymore.

**Comment by 123zhen123** [comment]
> Thanks for bringing this to our attention
> 
> Not all ALFRED games are supported for ALFWorld. For instance, the movable ones are not supported as briefly mentioned in the [scripts/README.md](https://github.com/alfworld/alfworld/tree/master/scripts)
> 
> > it means the game is unsolvable or the PDDL problem is ill-defined. Some tasks from ALFRED like **movable receptacle** tasks are not used in ALFWorld, and will fail if you try to load them with alfworld-play-tw.
> 
> That said, those play scripts should raise an error when loading those games. I'll look into it.

Do you have plans to update the function of this piece recently?  It is still very useful and needed

**Comment by MarcCote** [comment]
We are not planning to add any new functionalities to ALFWorld.

Given that ALFWorld is now being used as a benchmark for many recent papers, changing the set of games could be problematic and lead to confusion.

Depending on which part of ALFWorld, you are interested in, [ScienceWorld](https://github.com/allenai/ScienceWorld) contains many more task variations of ranging complexity.
