### ISSUE TITLE
Error while running over remote server

### ISSUE THREAD

**Issue by Acejoy** [alfworld/alfworld#65]
Hey all, Thanks for the great work on ALFWORLD.  I am trying to run the alfworld over a remote server. I ran the following command after  installing alfworld from source.
`$ alfworld-play-thor $ALFWORLD_DATA/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller oracle_astar --debug`
I am getting the following error:
```
(alfworld) srinjoym@user:~/alfworld$ alfworld-play-thor $ALFWORLD_DATA/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller oracle_astar --debug
Playing '/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/'.
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  0
  Current serial number in output stream:  99
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/site-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/data/home/srinjoym/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '4', '-screen-width', '300', '-screen-height', '300'] exited with 1
```

Earlier before getting this error, I had another error because of different `DISPLAY` variable, my local computer's DISPLAY variable is `:1` but the remote server's DISPLAY variable value is `localhost:10.0`. The error I encountered here was:
```
(alfworld) srinjoym@user:~/alfworld$ alfworld-play-thor $ALFWORLD_DATA/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller oracle_astar --debug
Playing '/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/'.
Authorization required, but no authorization protocol specified
xdpyinfo:  unable to open display ":0".
Traceback (most recent call last):
  File "/data/home/srinjoym/miniconda3/envs/alfworld/bin/alfworld-play-thor", line 109, in <module>
    main(args)
  File "/data/home/srinjoym/miniconda3/envs/alfworld/bin/alfworld-play-thor", line 43, in main
    env = ThorEnv()
  File "/data/home/srinjoym/alfworld/alfworld/env/thor_env.py", line 38, in __init__
    self.start(x_display=x_display,
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/site-packages/ai2thor/controller.py", line 855, in start
    self.check_x_display(env['DISPLAY'])
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/site-packages/ai2thor/controller.py", line 714, in check_x_display
    assert subprocess.call("xdpyinfo", stdout=dn, env=env, shell=True) == 0, \
AssertionError: Invalid DISPLAY :0 - cannot find X server with xdpyinfo

```

I solved the error (after ssh -X remote_ip) as follows:
```
export DISPLAY=:1

alfworld-play-thor $ALFWORLD_DATA/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller oracle_astar --debug
```

The configurations of my remote server is as follows:
```
RAM: 125 GB
CUDA VERSION:12.2
VRAM: 49GB
```

Any help is greatly appreciated. Thanks

**Comment by AshisGhosh** [comment]
This proved to help: https://github.com/alfworld/alfworld/issues/39#issuecomment-2055860114

**Comment by Acejoy** [comment]
Thanks for the quick reply @AshisGhosh , but I solved that problem, as you can see in second part of the question description I wrote. The current problem I am facing is the top error( referring to " Bad Alloc.....").

**Comment by Acejoy** [comment]
Thanks for the reply @MarcCote . This is the output for `glxgears`:
```
Command 'glxgears' not found, but can be installed with:
apt install mesa-utils
Please ask your administrator.
```

and for `python docker/check_thor.py`:
```
Found path: /data/home/srinjoym/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/data/home/srinjoym/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/data/home/srinjoym/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1920x1080 (primary device).
Logging to /data/home/srinjoym/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
(300, 300, 3)
Everything works!!!
```

**Comment by MarcCote** [comment]
Do you get any windows with Unity logo popping up, like this?
![image](https://github.com/alfworld/alfworld/assets/660004/875371a5-cd50-4657-99db-14dae7cba1fd)

**Comment by MarcCote** [comment]
You might also want to install `apt install mesa-utils` to debug things.

**Comment by Acejoy** [comment]
> Do you get any windows with Unity logo popping up, like this? ![image](https://private-user-images.githubusercontent.com/660004/331265271-875371a5-cd50-4657-99db-14dae7cba1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzU0NDQsIm5iZiI6MTcxNTg3NTE0NCwicGF0aCI6Ii82NjAwMDQvMzMxMjY1MjcxLTg3NTM3MWE1LWNkNTAtNDY1Ny05OWRiLTE0ZGFlN2NiYTFmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNTU5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2E4Yjg5ZGZjMTkzNzMxZDU4NGUwNDM4YTBmNTRiNDNlYmMyMzhmMTY5NGNiMTdjNTAwOTU2OGRhYTEyODZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0qWoqh2XV6JJ8VkAsUEduuvj1hOYpK62EkwRwCYN-AM)

yes, while running `python docker/check_thor.py` I am getting a unity window.

**Comment by Acejoy** [comment]
> You might also want to install `apt install mesa-utils` to help with debugging this.

Okay I installed mesa-utils now and glxgears is working.

![Screenshot from 2024-05-16 21-42-01](https://github.com/alfworld/alfworld/assets/36639911/072910a9-ef38-432a-80e4-c909fc39a42f)

**Comment by Acejoy** [comment]
@AshisGhosh @MarcCote , thanks for the help guys, I was finally able to fix the problem. So I had to change the X_DISPLAY constant in alfworld/gen/constants.py. I remote login to my server and used the following command `echo $DISPLAY`, the output was `localhost:11.0`.

So I changed X_DISPLAY to 11. and then it worked.
I am not sure , why it works though, it will be great if you could explain it.

**Comment by MarcCote** [comment]
Ok, that's weird. So, I tried your command on my remote machine and it works.

    alfworld-play-thor $ALFWORLD_DATA/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988/ --controller oracle_astar --debug

Have you tried other games? Are they also crashing with the same error?

**Comment by Acejoy** [comment]
Yes, I tried playing different games and it worked with no problem.
