### ISSUE TITLE
Regarding Training of MRCNN for Segmentation

### ISSUE THREAD

**Issue by Acejoy** [alfworld/alfworld#67]
Hey all, I was playing around with the trained mrcnn model, the weights I am using is mrcnn_alfred_objects_sep13_004.pth. I want to know the evaluation metrics of the trained model (like IoU and mAP). 

Also, I would like to know how the different model weights listed [here](https://github.com/alfworld/alfworld/releases/tag/0.2.2) are different from the above.

I was playing the following game:pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988. In this game, I noticed the mrcnn_astar controller couldn't find the potato(it detected it as a pillow(?)).

I am attaching the output segments of mrcnn.
![Screenshot from 2024-05-20 18-04-44](https://github.com/alfworld/alfworld/assets/36639911/3e03fe75-f450-40f5-afb0-4085c2494171)

Also, the following is the output from textworld engine when it went to sink 1:
You arrive at loc 14. On the sinkbasin 1, you see a faucet 1, a dishsponge 1, a cup 1, a mug 1, a knife 1, a spoon 1, a bowl 1, a pillow 1, a peppershaker 1, and a spatula 1.

Thanks.

**Comment by MarcCote** [comment]
Hi @Acejoy, I might be playing the wrong game but when I load
`alfworld-play-tw ~/.cache/alfworld/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_05498`

I see the following:
```
Playing '~/.cache/alfworld/json_2.1.1/train/pick_heat_then_place_in_recep-Potato-None-SinkBasin-14/trial_T20190908_231731_054988'.
-= Welcome to TextWorld, ALFRED! =-

You are in the middle of a room. Looking quickly around you, you see a cabinet 8, a cabinet 7, a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 2, a countertop 1, a fridge 1, a garbagecan 1, a microwave 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1.

Your task is to: heat some potato and put it in sinkbasin.
Oracle: [None/None|(None): go to coffeemachine 1 > take potato 2 from countertop 2 > go to microwave 1 > heat potato 2 with microwave 1 > go to sinkbasin 1 > put potato 2 in/on sinkbasin 1]

> go to sinkbasin 1
You arrive at loc 8. On the sinkbasin 1, you see a dishsponge 3, a egg 2, and a knife 3.
Oracle: [0/None|(None): go to coffeemachine 1 > take potato 2 from countertop 2 > go to microwave 1 > heat potato 2 with microwave 1 > go to sinkbasin 1 > put potato 2 in/on sinkbasin 1]

>
```

I don't see a pillow. Looking at the oracle trajectory, I see one potato is located on the `countertop 2`.

**Comment by Acejoy** [comment]
Hey, sorry for the late update, But I moved on from this project , but as far as I remember, the error lies in the mrcnn(?)because in the image above you see the potato in bottom left is being detected as pillow. Not sure why though.
Also, I should have added the entire trajectory(sorry fo that).

Hope that helps.
