### ISSUE TITLE
Does the ALFWORLD environment need to connect to the internet to interact with the environment?

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [alfworld/alfworld#68]
alfworld-play-thor

Does the ALFWORLD environment need to connect to the internet to interact with the environment? When I execute the
“alfworld-play-thor” command, it shows the following:

Playing
'path/alfworld/json_2.1.1/train/pick_and_place_with_movable_recep-Pencil-Bowl-CoffeeTable-203/trial_T20190908_122736_052563'.

Could you provide the download link for this? Because I cannot connect to the external network.
I deeply apologize for this.

**Comment by MarcCote** [comment]
You need to download the data only once (see https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart).

```
export ALFWORLD_DATA=<storage_path>
alfworld-download
```

**Comment by xiaxiaxiatengxi** [comment]
> You need to download the data only once (see https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart).
> 
> ```
> export ALFWORLD_DATA=<storage_path>
> alfworld-download
> ```
Thank you for your reply. I have downloaded the necessary files, but I am now encountering a new problem.

My environment is a cluster environment where we are unable to install an X server. I planned to simulate the X server using xvfb-run during startup. However, in **ai2thor/controller.py at line 1182
self.last_event = self.server.receive(),** 
I am unable to receive any messages and it gets stuck at this point.

Is it not possible to execute commands on the cluster?

My versions are: ai2thor==3.1.0 alfworld==0.3.4

The command I executed is as follows:
`xvfb-run -s "-screen 0 300x300x24" accelerate launch --config_file config_zero2.yaml --main_process_port 29330 ../main_alf.py`
The main_alf.py code is as follows:

import other packages
from alfworld.agents.environment.alfred_thor_env import AlfredThorEnv
env = AlfredThorEnv(config, train_eval='train')
env.init_env(batch_size=1)

**Comment by MarcCote** [comment]
As listed in the [requirements.txt](https://github.com/alfworld/alfworld/blob/master/requirements.txt) the ai2thor version needs to be 2.1.0.

Assuming you indeed have 2.1.0, I invite you to try the following procedure in the Readme.
https://github.com/alfworld/alfworld?tab=readme-ov-file#run-headless

Also, can you paste the output of your `Player.log` (the complete should be printed upon launching ai2thor).

**Comment by xiaxiaxiatengxi** [comment]
> As listed in the [requirements.txt](https://github.com/alfworld/alfworld/blob/master/requirements.txt) the ai2thor version needs to be 2.1.0.
> 
> Assuming you indeed have 2.1.0, I invite you to try the following procedure in the Readme. https://github.com/alfworld/alfworld?tab=readme-ov-file#run-headless
> 
> Also, can you paste the output of your `Player.log` (the complete should be printed upon launching ai2thor).

Wow!! Thank you for your help. I will give it a try. Since my cluster cannot access external networks, configuring the environment is quite troublesome.

**Comment by MarcCote** [comment]
Even though you don't have a X Server, you would need to install opengl to actually render the images.

I think you best bet is to use a docker image (see the relevant section in the Readme).

**Comment by xiaxiaxiatengxi** [comment]
> Even though you don't have a X Server, you would need to install opengl to actually render the images.
> 
> I think you best bet is to use a docker image (see the relevant section in the Readme).

Oh, thank you, I will try docker image

**Comment by MarcCote** [comment]
Any success using the docker image?
