### ISSUE TITLE
Alfworld not thread-safe across different environments? (in python)

### ISSUE THREAD

**Issue by okhat** [alfworld/alfworld#71]
Thanks for the awesome work. I made a careful wrapper around Alfworld that I thought would allow me to run multiple envs across (parallel) threads in Python. The threads will act and make LM calls concurrently.

```python
import io
import yaml
import alfworld
import alfworld.agents.environment
from contextlib import redirect_stdout, redirect_stderr

with open('base_config.yaml') as reader: config = yaml.safe_load(reader)
    
def alfworld_datapoint(idx):
    def env_fn():
        output_buffer = io.StringIO()

        with redirect_stdout(output_buffer), redirect_stderr(output_buffer):
            split = "eval_in_distribution" # has 140 tasks
            env = alfworld.agents.environment.AlfredTWEnv(config, train_eval=split)
            env = env.init_env(batch_size=1)
            env.skip(idx)
            task_definition, info = env.reset()

        return env, task_definition, info

    return env_fn
```

Without threading, everything works fine. Unfortunately, when I use threading, I see a lot of weird corruption errors when thread 0 works on `alfworld_datapoint(0)()` and thread 2 works on `alfworld_datapoint(1)()`.

Is this a fundamental limitation, no multi-threading even across completely separated envs?

**Comment by MarcCote** [comment]
Hi Omar! Nice to see you here. I don't know if ai2thor support multithreading, but I can say that TextWorld does not. 

That being said, TextWorld does support multiprocessing and is used here
https://github.com/alfworld/alfworld/blob/master/alfworld/agents/environment/alfred_tw_env.py#L271-L275

**Comment by okhat** [comment]
Ah, thanks for the helpful response @MarcCote !

Multi-threading is essential for me, so perhaps one thing I can do is make each thread create a new process that creates its own new env and to talk to that env through the new process.
