### ISSUE TITLE
how to fix an environment?

### ISSUE THREAD

**Issue by tinaa4869** [alfworld/alfworld#72]
Hi, authors! thanks for your great work!

alfworld has been used in many works related to LLM decision making, such as [ReAct](https://github.com/ysymyth/ReAct), [ExpeL](https://github.com/LeapLabTHU/ExpeL). However, when I run code in these works about alfworld multiple times, I have known that alfworld will load a different layout in each run. But I want to make different runs‘ result comparable, so I'd like to make the environments layout fix. How can I do that?

For example. here is the code about set an alfworld environment in [ExpeL](https://github.com/LeapLabTHU/ExpeL) : 

```
import re
from typing import List, Dict, Any, Tuple
from envs.base import BaseEnv

import alfworld.agents.environment
from utils import get_env_name_from_gamefile

class AlfworldEnv(BaseEnv):
    def __init__(self,
                gamefile: str,
                config: Dict[str, Any],
                max_steps: int = 50,
                ):
        self.max_steps = max_steps
        self.gamefile = gamefile
        self.config = config
        self.main_env = getattr(alfworld.agents.environment, self.config.env.type)(self.config, train_eval=self.config.split)
        self.main_env.game_files = [self.gamefile]
        self.task = "housekeeper robot. The agent was placed in a household environment and a task to complete."
        self.env_name = get_env_name_from_gamefile(gamefile)

        self.reset()

    def reset(self):
        self.curr_step = 1
        self.answer = ''
        self.terminated = False
        self.reward = False
        self.is_exhausted = False
        self.env = self.main_env.init_env(batch_size=1)
        self.env.reset()
        self.last_action = None
```

How can I modify the code or configs to make the environment's layout fix?

Maybe a silly question😂I will be very appreciated if I can receive your reply. thank u!!!

**Comment by MarcCote** [comment]
Hi @tinaa4869, maybe that's a question @Andrewzh112 can help answer.

The environment returned by `self.env = self.main_env.init_env(batch_size=1)` can be seeded as [follows](https://github.com/microsoft/TextWorld/blob/main/textworld/gym/envs/textworld_batch.py#L82) `self.env.seed(20240621)` to guarantee the order in which the games are played.

The thing I'm not I understand is that in the provided code above, it looks like you have a single game. So, I'm a bit puzzled by your observation. Without a fully working code example, it would be hard for me to provide more information.

**Comment by tinaa4869** [comment]
> Hi @tinaa4869, maybe that's a question @Andrewzh112 can help answer.
> 
> The environment returned by `self.env = self.main_env.init_env(batch_size=1)` can be [seeded](https://github.com/microsoft/TextWorld/blob/main/textworld/gym/envs/textworld_batch.py#L82) as follows `self.env.seed(20240621)` to guarantee the order in which the games are played.
> 
> The thing I'm not I understand is that in the provided code above, it looks like you have a single game. So, I'm a bit puzzled by your observation. Without a fully working code example, it would be hard for me to provide more information.

thanks for your reply!!! Although my expression may be a bit confusing, your answer has addressed part of my questions about how to guarantee the order of games are played.

I still have question that if I set env.seed(20240621), the environment's layout has also been fixed? For example, what I see in this environment, what objects put on the task are the same whenever I reset the environment with the same seed?

thanks again for your help!!!
