### ISSUE TITLE
Can not Install Alfworld.

### ISSUE THREAD

**Issue by Cu2ta1n** [alfworld/alfworld#74]
hello！I first navigated to the alfworld directory and then ran python setup.py install, but encountered the following error:
`subprocess.CalledProcessError: Command '['python', 'build.py', '--library']' returned non-zero exit status 1.`，Then I try to use a method you have released in the issues,
`apt install cmake # Needed for compiling fast-downward
conda create -n alfworld36 python=3.6
conda activate alfworld36
git clone https://github.com/alfworld/alfworld.git alfworldcd alfworld
pip install -r reguirements.txt
pip install .
alfworld-download
alfworld-play-tw`
But I failed in the last step. `alfworld-play-tw`
The error is `Traceback (most recent call last):
  File "/data2/Anaconda3/envs/emma/bin/alfworld-play-tw", line 17, in <module>
    from alfworld.agents.environment.alfred_tw_env import AlfredExpert, AlfredDemangler, AlfredExpertType
  File "/data2/Anaconda3/envs/emma/lib/python3.11/site-packages/alfworld/agents/environment/__init__.py", line 2, in <module>
    from alfworld.agents.environment.alfred_thor_env import AlfredThorEnv
  File "/data2/Anaconda3/envs/emma/lib/python3.11/site-packages/alfworld/agents/environment/alfred_thor_env.py", line 17, in <module>
    from alfworld.agents.detector.mrcnn import load_pretrained_model
  File "/data2/Anaconda3/envs/emma/lib/python3.11/site-packages/alfworld/agents/detector/mrcnn.py", line 1, in <module>
    import torch
  File "/data2/Anaconda3/envs/emma/lib/python3.11/site-packages/torch-2.3.1-py3.11-linux-x86_64.egg/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory`
Then I install the cudnn again, but it didn't work.
Finnally, I build a new env and this time I failed in the step `pip install -r reguirements.txt`,the error is 
` ERROR: Failed building wheel for textworld
Failed to build textworld
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (textworld)`

**Comment by MarcCote** [comment]
Hi. Looking at your error message, it seems you are using the `emma` conda env, is that on purpose?

**Comment by Cu2ta1n** [comment]
> Hi. Looking at your error message, it seems you are using the `emma` conda env, is that on purpose?

Ohhh! I just ran it successfully! Although I don't know how he succeeded either. (･_･;)

**Comment by MarcCote** [comment]
That's great. My question about the conda env was "why are you using `emma` instead of the `alfworld36` env you just created.". Also, note that recent version of ALFWorld doesn't need Python 3.6 now.
