### ISSUE TITLE
Question about Retrieving Action Costs in ALFWorld

### ISSUE THREAD

**Issue by dekun-jack-wu** [alfworld/alfworld#76]
Hi, I have a question regarding retrieving action costs in ALFWorld. I noticed that the total-cost and distance functions are defined in the alfred.pddl file, and that each action, such as "pick up" or "go to," increases the total-cost. However, I am unable to retrieve the total-cost or the cost of executing each admissible command from the environment, i.e., via env.step().

Is there a method or approach that would allow me to easily obtain the cost information for these actions? Any guidance would be greatly appreciated.

Thank you!

**Comment by dekun-jack-wu** [comment]
Thank you for your previous response regarding the use of total-cost. I understand that ALFWorld doesn't utilize total-cost. I am wondering if there is a straightforward way, similar to how the inventory command retrieves boolean values of predicates, to easily obtain the numerical values of functions like total-cost via natural language commands.

The reason I am asking is that I plan to extend ALFWorld to include features such as an energy or stamina value for the agent. This stamina value is expected to decrease with each action and require the agent to perform a rest action (which I plan to define) to restore stamina before continuing with other actions.

Is it possible to retrieve the values of such functions through modifications to the twl2 file, the domain file (alfred.pddl), and the problem file (initial_state.pddl)? If this isn't feasible within the current framework, I might need to explore alternative approaches.

Any insights or suggestions you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by MarcCote** [comment]
Unfortunately, the current implementation of TextWorld doesn't support non boolean facts. It exclusively relied on binary predicate logic.

**Comment by dekun-jack-wu** [comment]
Thanks.
