### ISSUE TITLE
Correction for put action "in / on" to "in/on"

### ISSUE THREAD

**Issue by ai-nikolai** [alfworld/alfworld#78]
We observed that the action `put` only allows for very specific syntax, namely `put object in/on place`. Using `put object in place` or put object on place` results in an error. 

This causes a big performance drop for some LLM-based agents.

Is there any plan to address such fixes (or collect such issues)?

@MarcCote

**Comment by MarcCote** [comment]
There's no plan to fix this at the moment. Maybe a quick hack along those lines would be do the trick
`action = action.replace('in', 'in/on').replace('on', 'in/on') if action.startswith('put') else action` ?

Also, not that ALFWorld is not a proper text-based games with meaningful error feedback messages, I'd suggest using the [TextWorld cooking games](https://textworld.readthedocs.io/en/stable/textworld.challenges.cooking.html), [ScienceWorld](https://github.com/allenai/ScienceWorld) or even [DiscoveryWorld](https://github.com/allenai/discoveryworld) to some extent for this.

**Comment by ai-nikolai** [comment]
Thanks for the quick and great response. 

Could you elaborate on "meaningful error feedback messages"? Do you mean the other envs you mentioned actually provide text based feedback of the type "Sorry, you can't do XYZ".

**Comment by MarcCote** [comment]
For instance trying to open a door twice will tell you it is already open.

![image](https://github.com/user-attachments/assets/0cf8364a-630a-4559-9323-cd8625a2b4f6)


You can give it a try here
https://aka.ms/textworld-tryit

**Comment by ai-nikolai** [comment]
Thank you very much. That's very helpful and good to know.
