### ISSUE TITLE
Getting OS Error while using alfworld

### ISSUE THREAD

**Issue by jabhinav** [alfworld/alfworld#79]
Hi authors, I have installed alfworld on my M2 mac but running into the following issue by running the command `alfworld-play-tw`

OSError: dlopen(/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so, 0x0006): tried: '/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (no such file), '/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/private/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (no such file), '/private/var/folders/3h/2k_5t4r95b307pgr61qv_6d80000gn/T/tmpusl5k5hp/libdownward.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

Can you please help?

**Comment by MarcCote** [comment]
Are you using a dedicated conda environment to install alfworld? e.g.,

    CONDA_SUBDIR=osx-64 conda create -n alfworld python=3.9 

What command did you use to install alfworld?

Also, can you try to reinstall 

    pip install --upgrade --force-reinstall fast-downward-textworld

**Comment by jabhinav** [comment]
Hi, Thanks for sharing the fix. I did not use the prefix `CONDA_SUBDIR=osx-64` while creating the environment. Doing so fixed the problem. Appreciate your quick response.

**Comment by MarcCote** [comment]
I'm not using MacOS so it is hard for me to debug those issue. My understanding of the error was that the binary file for the downward library was generated for Intel architecture instead of arm but your conda environment was created for arm.
See ref: https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple

**Comment by MarcCote** [comment]
I have added a note regarding this in the Quickstart section.
https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart
