### ISSUE TITLE
Can't reduce repo size with BFG cleaner

### ISSUE THREAD

**Issue by MohitShridhar** [alfworld/alfworld#8]
@MarcCote, I tried out reducing the repo size with BFG cleaner. But I couldn't push the changes:

```
To https://github.com/alfworld/alfworld.git
 ! [remote rejected] refs/pull/7/head -> refs/pull/7/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/7/merge -> refs/pull/7/merge (deny updating a hidden ref)
```

From [this](https://stackoverflow.com/questions/50343697/cleaning-git-repository-bfg-repo-cleaner-repo-size-is-still-large-after-i-pu), it looks like there is no easy way to resolve this.  Do you have any other suggestions? Or should we leave it as is.

**Comment by MarcCote** [comment]
Hmm. I thought you only needed to force-push it. Let's do it together Monday.

**Comment by MarcCote** [comment]
I just tried to `git clone` this repo and the size if way smaller. So, I'd say it has worked.
