### ISSUE TITLE
How can i modify the goal condition

### ISSUE THREAD

**Issue by khm159** [alfworld/alfworld#81]
Hello, thank you for your excellent work!

Since I'm not very familiar with PDDL or text game, I would like to know where to start if I only want to modify the goal condition. I want to keep the same scenes and initial state and actions but change the goal condition.
And is there any tools print pddl-tw files?

Thank you once again!

**Comment by MarcCote** [comment]
Hi, pddl-tw are generated by ALFWorld (here's an example https://github.com/alfworld/alfworld/blob/master/scripts/alfworld-play-tw#L35-L37). It is a merge of PDDL problem, PDDL domain and TW grammar file.

To change the goal, open any of the .pddl file in the alfworld cache folder and you can edit it manually.

**Comment by khm159** [comment]
Thank you for your explanation!
