### ISSUE TITLE
Error when running command 'alfworld-play-thor'

### ISSUE THREAD

**Issue by GasolSun36** [alfworld/alfworld#85]
Hi,

Thanks for your excellent work! However, I enconuter some issues:

When I install the environment, I run the command `alfworld-play-thor`, and I get:

> Traceback (most recent call last):
  File "/opt/anaconda3/envs/alfworld1/bin/alfworld-play-thor", line 137, in <module>
    args.problem = os.path.dirname(random.choice(problems))
  File "/opt/anaconda3/envs/alfworld1/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

I have no idea what happened. Can your help me with that?

**Comment by MarcCote** [comment]
Hi @GasolSun36 

So, I can better understand your setup, did you run `alfworld-download` after installing alfworld as mentioned in the [README](https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart)?

Also, does the command `alfworld-play-tw` works for you?

**Comment by GasolSun36** [comment]
> Hi @GasolSun36
> 
> So, I can better understand your setup, did you run `alfworld-download` after installing alfworld as mentioned in the [README](https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart)?
> 
> Also, does the command `alfworld-play-tw` works for you?

Hi,

1. Yes, I think I install the environment correctly, since I can run `run_eval.py` normally.

2. Yes, `alfworld-play-tw` command works for me, but `alfworld-play-thor` didn't work.

**Comment by yanxue7** [comment]
I also meet a similar problem:

`  File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/dlp/lib/python3.10/site-packages/alfworld/agents/environment/alfred_tw_env.py", line 102, in step
    self._gather_infos()
  File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/dlp/lib/python3.10/site-packages/alfworld/agents/environment/alfred_tw_env.py", line 82, in _gather_infos
    handcoded_expert_next_action = self._handcoded_expert.act(self.state, 0, self.state["won"], self.prev_command)
  File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/dlp/lib/python3.10/site-packages/alfworld/agents/expert/handcoded_expert.py", line 562, in act
    action = self.policy.act(game_state, last_action)
  File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/dlp/lib/python3.10/site-packages/alfworld/agents/expert/handcoded_expert.py", line 318, in act
    obj = random.choice(objs_of_interest)
  File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/dlp/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
`

**Comment by MarcCote** [comment]
Hi @yanxue7 your issue seems different from @GasolSun36. In your case, it seems the handcoded expert is failing to pick a random object. i.e.
> obj = random.choice(objs_of_interest)

In @GasolSun36's case, the issues come from selecting a random problem from the `~/.cache/alfworld/json_2.1.1/train`. @GasolSun36 can you confirm the data is there?

**Comment by MarcCote** [comment]
@yanxue7 What was the command you ran? Can you share the full output not just the error.

**Comment by GasolSun36** [comment]
> Hi @yanxue7 your issue seems different from @GasolSun36. In your case, it seems the handcoded expert is failing to pick a random object. i.e.
> 
> > obj = random.choice(objs_of_interest)
> 
> In @GasolSun36's case, the issues come from selecting a random problem from the `~/.cache/alfworld/json_2.1.1/train`. @GasolSun36 can you confirm the data is there? You can try to install #86 and see what's the error message.
> 
> ```
> pip install https://github.com/alfworld/alfworld/archive/refs/heads/add_warning_msg.zip
> ```

Hi, Thanks for your reply! Actually, I download the data in alfworld folder, the project hierarchy looks like this:

- alfworld
    - data
        - agents
        - detectors
        - json_2.1.1
            - train
            - valid_seen
            - valid_train
            - valid_unseen
    - alfworld
    - configs
    - ...

If I understand correctly, these files need to be placed under `~/.cache/alfworld`? Because currently there is nothing under my `~/.cache/alfworld` directory.

BTW, I install the `add_warning_msg.zip` and it didn't change anything. Still the same error without additional info:

> Traceback (most recent call last):
File "/opt/anaconda3/envs/alfworld1/bin/alfworld-play-thor", line 137, in
args.problem = os.path.dirname(random.choice(problems))
File "/opt/anaconda3/envs/alfworld1/lib/python3.10/random.py", line 378, in choice
return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by MarcCote** [comment]
Interesting. Did you make sure the environment variable `ALFWORLD_DATA` is pointing to that data folder? 

re: add_warning_msg.zip, I'm very puzzled by this. If the installation did complete correctly, it should have installed a new `alfworld-play-thor` script. Can you try to uninstall the previous version first.

    pip uninstall alfworld
    pip install https://github.com/alfworld/alfworld/archive/refs/heads/add_warning_msg.zip

**Comment by GasolSun36** [comment]
> Interesting. Did you make sure the environment variable `ALFWORLD_DATA` is pointing to that data folder?
> 
> re: add_warning_msg.zip, I'm very puzzled by this. If the installation did complete correctly, it should have installed a new `alfworld-play-thor` script. Can you try to uninstall the previous version first.
> 
> ```
> pip uninstall alfworld
> pip install https://github.com/alfworld/alfworld/archive/refs/heads/add_warning_msg.zip
> ```

Yes, I'm positive I set the correct ALFWORLD_DATA variable. Meanwhile, I have another question, can I turn off the display completely? I face the issue: `AssertionError: Invalid DISPLAY :0.0 - cannot find X server with xdpyinfo`. I think I do not need to visualize the environment.

**Comment by MarcCote** [comment]
> Yes, I'm positive I set the correct ALFWORLD_DATA variable. 
I get that you have set ALFWORLD_DATA when calling `alfworld-data` but this means that every time you use alfworld scripts, you will need to ensure that ALFWORLD_DATA is pointing to the right place.

    echo $ALFWORLD_DATA

> Meanwhile, I have another question, can I turn off the display completely? I face the issue: `AssertionError: Invalid DISPLAY :0.0 - cannot find X server with xdpyinfo`. I think I do not need to visualize the environment.

If you don't need the images (i.e., the text-only version), then you need to use the non thor environments, i.e. `alfworld/agents/environment/alfred_tw_env.py:AlfredTWEnv` and `alfworld-tw-play`.

If you do need the images but don't want it to show up, you can use tool like `xvfb-run` (see https://en.wikipedia.org/wiki/Xvfb) but AI2THOR does require a X server to generate the images.

**Comment by GasolSun36** [comment]
> > Yes, I'm positive I set the correct ALFWORLD_DATA variable.
> > I get that you have set ALFWORLD_DATA when calling `alfworld-data` but this means that every time you use alfworld scripts, you will need to ensure that ALFWORLD_DATA is pointing to the right place.
> 
> ```
> echo $ALFWORLD_DATA
> ```
> 
> > Meanwhile, I have another question, can I turn off the display completely? I face the issue: `AssertionError: Invalid DISPLAY :0.0 - cannot find X server with xdpyinfo`. I think I do not need to visualize the environment.
> 
> If you don't need the images (i.e., the text-only version), then you need to use the non thor environments, i.e. `alfworld/agents/environment/alfred_tw_env.py:AlfredTWEnv` and `alfworld-tw-play`.
> 
> If you do need the images but don't want it to show up, you can use tool like `xvfb-run` (see https://en.wikipedia.org/wiki/Xvfb) but AI2THOR does require a X server to generate the images.

Thanks, I think I understand. Meanwhile, there still a problem. There is a description to the environment, e.g. "Welcome to TextWorld, ALFRED! =- You are in the middle of a room. Looking quickly around you, you see a cabinet 1, a cabinet 2, a cabinet 3, a cabinet 4, a cabinet 5, a cabinet 6, a cabinet 7, a cabinet 8, a coffeemachine 1, a countertop 1, a countertop 2, a countertop 3, a drawer 1, a drawer 2, a drawer 3, a drawer 4, a drawer 5, a drawer 6, a drawer 7, a drawer 8, a drawer 9, a fridge 1, a garbagecan 1, a microwave 1, a shelf 1, a shelf 2, a shelf 3, a sink 1, a sinkbasin 1, a stoveburner 1, a stoveburner 2, a stoveburner 3, a stoveburner 4, and a toaster 1"

I was wandering how to distinguish between drawer1 and drawer2, for vlm? Is there any tool needed?

**Comment by MarcCote** [comment]
There's no tool readily available to do it. You probably want to have a look at this thread: https://github.com/alfworld/alfworld/issues/63

**Comment by MarcCote** [comment]
I will be closing this as the main issue is resolved. If not, feel free to re-open. For your more recent problem, let's continue the discussion over the other issue 63.

**Comment by ShuaiLyu0110** [comment]
> Hi [@yanxue7](https://github.com/yanxue7) your issue seems different from [@GasolSun36](https://github.com/GasolSun36). In your case, it seems the handcoded expert is failing to pick a random object. i.e.
> 
> > obj = random.choice(objs_of_interest)
> 
> In [@GasolSun36](https://github.com/GasolSun36)'s case, the issues come from selecting a random problem from the `~/.cache/alfworld/json_2.1.1/train`. [@GasolSun36](https://github.com/GasolSun36) can you confirm the data is there? You can try to install [#86](https://github.com/alfworld/alfworld/pull/86) and see what's the error message.
> 
> ```
> pip install https://github.com/alfworld/alfworld/archive/refs/heads/add_warning_msg.zip
> ```

Thank you for your excellent work. I’m trying to reproduce the ALFWorld experiment from your paper using this repository.

I followed the instructions strictly and did not modify the code, but I consistently encounter an error during epoch 6. Please see the attached screenshot for details.

Could you please advise what might be causing this issue? Any help would be greatly appreciated!

![Image](https://github.com/user-attachments/assets/b4e3ab6f-6c5e-407d-b2ae-2036a48c8006)
