### ISSUE TITLE
no matches found: [full] - pip install issue; python3.9

### ISSUE THREAD

**Issue by ai-nikolai** [alfworld/alfworld#88]
**Python:**
`Python 3.9.20`

**Pip:**
`pip 24.2 from /lib/python3.9/site-packages/pip (python 3.9)`

**How to replicate:**
```
pip3 install alfworld[full]
```

**Error Output:**
```
zsh: no matches found: alfworld==0.3.5[full]
```

**Desired outcome:**
`Successfully installed alfworld[full]` (or similar)

**Comment by ai-nikolai** [comment]
Thank you for all the help. @MarcCote .

The reason for posting this problem as well is that currently when loading alfworld (after clean installation, i.e.: `pip install alfworld`). 

I get: 
```
Initializing AlfredTWEnv...
0it [00:00, ?it/s]
Overall we have 0 games in split=eval_out_of_distribution
Evaluating with 0 games
```

**Comment by MarcCote** [comment]
Hi @ai-nikolai, did you mean to do

    pip install alfworld[full]==0.3.5

On Bash, I would get this error message with your command.
```bash
> pip install alfworld==0.3.5[full]
ERROR: Extras after version '==0.3.5[full]'.
```

**Comment by MarcCote** [comment]
> ```
> Initializing AlfredTWEnv...
> 0it [00:00, ?it/s]
> Overall we have 0 games in split=eval_out_of_distribution
> Evaluating with 0 games
> ```

What command did you run for getting this?

**Comment by MarcCote** [comment]
Did you install the `alfworld-data`?

**Comment by MarcCote** [comment]
I meant `alfworld-download` as mentioned in the readme. 

    export ALFWORLD_DATA=<storage_path>
    alfworld-download

**Comment by ai-nikolai** [comment]
Hey @MarcCote , 

Thanks for following up and the quick responses. (Sorry for my slow response, I meant to write back on Monday alread.)

**Current Status:**
1. `pip3 install alfworld[full]` still throws an error for me: `zsh: no matches found: alfworld[full]==0.3.5` (python 3.12 & python 3.9, did not test others). (Also tried `pip3 install alfworld[all]` (just in case ;) ).
2. Alfworld itself, however, works perfectly. See below for more details:
---
**Getting Alfworld working:**
1. `pip3 install alfworld`
2. Following Readme more carefully. (My mistake).
Yes, so there were a couple of things I had missed with the new version  & `README.md`. The following I did not realise or forgot to do:

**Concrete Things I did:**
1. Download the data
```bash
alfworld-download
``` 
(I think it also worked without exporting the path.)

2. Using the new suggested way of importing the config file (`config = generic.load_config()`), requires passing the parameter and config file. (I guess it was hidden under the main code part in your README).
```bash
python your_file.py base_config.yaml
```
In the end I resorted back to the old way: (as I have other command line args and I did not want to mix them.):
```python
    with open('playgrounds/base_config.yaml') as reader:
        config = yaml.safe_load(reader)
    env_type = config['env']['type'] # 'AlfredTWEnv' or 'AlfredThorEnv' or 'AlfredHybrid'

    # setup environment
    env = getattr(environment, env_type)(config, train_eval=split)
    env = env.init_env(batch_size=1)
```
---
**A few small suggestions:**
1. Small updates to the README.md to make some of the above parts a bit clearer, specifically:
   - Making the command line argument for the config clearer (and that one needs to actually download that separately, for those that do not know).
   - Perhaps making it work without specifying the `ALFWORLD_DATA` 
   - pip install withou the [full] option. 
2. Introducing a default config into the repo. So that the command `generic.load_config()` works without an external config file. (Or by adding the config into the `alfworld-download` files so it gets downloaded into the data file and the default path will be the datapath (but that probably is circular).
3. Otherwise the repo is really useful and amazing, thanks for the great work on all the *Worlds. ;)

---
P.s.
(That's our latest paper on it:
StateAct - on average +10% over ReAct using in-context-learning only)
- https://arxiv.org/abs/2410.02810

**Comment by MarcCote** [comment]
Thanks for the report and the suggestions. 

> (I think it also worked without exporting the path.)

Yes, it will default to ~/.cache/alfworld

> 1. `pip3 install alfworld[full]` still throws an error for me: `zsh: no matches found: alfworld[full]==0.3.5` (python 3.12 & python 3.9, did not test others). (Also tried `pip3 install alfworld[all]` (just in case ;) ).

Probably a zsh vs bash thing. Can you try with quotes, e.g.

    pip install "alfworld[full]"

> 2\. Introducing a default config into the repo.

Not sure I follow, default configs can be found in the configs folder.

> So that the command generic.load_config() works without an external config file.

That's a good idea. We could default to https://github.com/alfworld/alfworld/blob/master/configs/base_config.yaml

> P.s. (That's our latest paper on it: StateAct - on average +10% over ReAct using in-context-learning only)
> 
> * https://arxiv.org/abs/2410.02810

Thanks for sharing, will have a look.

**Comment by lollipopwsy** [comment]
@ai-nikolai Hello, after encountering the same '0it [00:00, ?it/s]' issue as you and then running 'alfworld-download', I successfully got it to display 'Initializing AlfredTWEnv...
100%|| 341/341 [00:00<00:00, 947.27it/s]
Overall we have 134 games in split=eval_out_of_distribution
Evaluating with 134 games', but it always displays 'Nothing happens'. Details are as follows: You are in the middle of a room. Looking quickly around you, you see a cabinet 6, a cabinet 5, a cabinet 4, a cabinet 3, a cabinet 2, a cabinet 1, a coffeemachine 1, a countertop 3, a countertop 2, a countertop 1, a drawer 3, a drawer 2, a drawer 1, a fridge 1, a garbagecan 1, a microwave 1, a shelf 3, a shelf 2, a shelf 1, a sinkbasin 1, a stoveburner 4, a stoveburner 3, a stoveburner 2, a stoveburner 1, and a toaster 1.
Your task is to: clean some bowl and put it in cabinet.
Sending prompt to model...
Received response: > think: To solve the task, I need to find a bowl, clean it with the sinkbasin, and then put it in one of the cabinets.  
> > think: To solve the task, I need to find a bowl, clean it with the sinkbasin, and then put it in one of the cabinets.
Nothing happens.
Sending prompt to model...
Response too short, retrying (attempt 1)...
Received response: OK. Let's start by finding a bowl. Bowls are likely to be found in the cabinets, on the countertops, or in the drawers. I will check the cabinets first, starting with cabinet 1.
> OK. Let's start by finding a bowl. Bowls are likely to be found in the cabinets, on the countertops, or in the drawers. I will check the cabinets first, starting with cabinet 1.
Nothing happens.
Sending prompt to model...
Received response: > go to cabinet 1  
> > go to cabinet 1
Nothing happens.
Sending prompt to model...
Received response: Let's continue with our search for a bowl. I'll check the next cabinet.
> Let's continue with our search for a bowl. I'll check the next cabinet.
Nothing happens.
Sending prompt to model...
Received response: > go to cabinet 2
> > go to cabinet 2
Nothing happens.
Sending prompt to model...
Received response: > go to cabinet 3  
> > go to cabinet 3
Nothing happens.
Sending prompt to model...
Received response: > go to cabinet 4  
> > go to cabinet 4
Nothing happens.
Sending prompt to model...
Received response: > go to cabinet 5  
> > go to cabinet 5
Nothing happens. Could you help me solve this? Thank you very much!

**Comment by MarcCote** [comment]
The expected command should not include the "> ".

**Comment by MarcCote** [comment]
You can use alfworld-play to try it yourself. Use <tab> <tab> to list all the available actions.
