### ISSUE TITLE
Change in “put” Action Syntax in Latest Alfworld Environment

### ISSUE THREAD

**Issue by Xyuan13** [alfworld/alfworld#96]
I have been using the latest version of the Alfworld environment and ran some example oracle plans. I noticed that the original “put xx in/on xx” action seems to have been updated to “move xx to xx”. 
['go to shelf 2', 'take mug 1 from shelf 2', 'go to desk 2', 'move mug 1 to desk 2']
Could you please confirm if such a change has been made?

Additionally:

- Were there any other changes to the available actions?
- Where can I find the latest documentation or description of the updated actions?

Thank you for your assistance!

**Comment by MarcCote** [comment]
Hi thanks for reaching out. You can see the latest changes here https://github.com/alfworld/alfworld/releases, in particular https://github.com/alfworld/alfworld/pull/94 for the change in the action space.

I will add a note in the README to mention this breaking change.

Did you notice oracle plans that can't be executed correctly?

**Comment by Xyuan13** [comment]
@MarcCote  Thank you for your reply.  Besides, I haven't done much testing yet, so I haven't come across any oracle plans that don't work correctly so far.

**Comment by Xyuan13** [comment]
Refer to https://github.com/alfworld/alfworld/pull/94 for the change in the action space.

**Comment by Xyuan13** [comment]
@MarcCote  Thank you for the reply.  Besides, I haven't done much testing yet, so I haven't come across any oracle plans that don't work correctly so far.

**Comment by jkkjjj** [comment]
I have encountered the same problem as well. Your response has been very helpful to me! Sincere Thanks!
