### ISSUE TITLE
Miss 2 environments during evaluation on "eval_out_of_distribution" set

### ISSUE THREAD

**Issue by Xyuan13** [alfworld/alfworld#98]
When I try to evaluate the agents on the evaluation set "eval_out_of_distribution", two environments cannot be loaded. Below is the relevant log:
```
-> Skipping missing solvable key! /ALFWorld_Data/json_2.1.1/valid_unseen/look_at_obj_in_light-Bowl-None-DeskLamp-308/trial_T20190907_133919_856963/game.tw-pddl
-> Skipping missing solvable key! /ALFWorld_Data/json_2.1.1/valid_unseen/pick_clean_then_place_in_recep-Pan-None-CounterTop-10/trial_T20190908_032543_712058/game.tw-pddl
Overall we have 132 games in split=eval_out_of_distribution

```
Is there anything wrong with the data?

**Comment by MarcCote** [comment]
Interesting. On my machine, when I look at those tw-pddl files, I do see a "solvable": true in them. Can you try replacing them with those find in https://github.com/alfworld/alfworld/releases/download/0.4.0/json_2.1.2_tw-pddl.zip. (maybe to be safe, delete all the .tw-pddl files and run the alfworld-download again?)

**Comment by Xyuan13** [comment]
@MarcCote Thank you for providing the updated tw-pddl files. Upon checking, I noticed that the tw-pddl files of the two game environments that could not be loaded missing the "solvable": true attribute. After replacing them with the new tw-pddl files you provided, everything is working well now.
